blueprint:
  name: Leak detection & notifier
  description: Run custom actions when a moisture sensor detects a leak
  domain: automation

  input:
    leak_detected_actions:
      name: Leak Detected Actions
      description: >
        Actions to run when a leak is detected.
        Can include mobile notifications, Alexa TTS, lights, sirens, etc.
      default: []
      selector:
        action: {}

trigger:
  - platform: event
    event_type: state_changed

condition:
  - condition: template
    value_template: >
      {{ trigger.event.data.new_state is not none }}

  - condition: template
    value_template: >
      {{ trigger.event.data.new_state.attributes.device_class == "moisture" }}

  - condition: template
    value_template: >
      {{ trigger.event.data.new_state.state == "on" }}

action:
  - variables:
      leak_sensor: >
        {{ trigger.event.data.new_state.attributes.friendly_name }}
      leak_message: >
        {{ leak_sensor }} has detected a leak.

  - sequence: !input leak_detected_actions

mode: single
