blueprint:
  name: Leak detection & notifier
  description: Run custom actions when a moisture sensor detects a leak
  domain: automation

  input:
    notify_devices:
      name: Mobile notify devices
      description: Devices to receive leak notifications
      default: []
      selector:
        device:
          integration: mobile_app
          multiple: true

    leak_detected_actions:
      name: Additional Leak Actions
      description: >
        Optional additional actions such as Alexa TTS,
        lights, sirens, scripts, etc.
      default: []
      selector:
        action: {}

trigger:
  - platform: event
    event_type: state_changed

condition:
  - condition: template
    value_template: >
      {{ trigger.event.data.new_state is not none }}

  - condition: template
    value_template: >
      {{ trigger.event.data.new_state.attributes.device_class == "moisture" }}

  - condition: template
    value_template: >
      {{ trigger.event.data.new_state.state == "on" }}

action:
  - variables:
      leak_sensor: >
        {{ trigger.event.data.new_state.attributes.friendly_name }}

      leak_message: >
        {{ leak_sensor }} has detected a leak.

      devices: !input notify_devices

  # Send notification to all selected mobile devices
  - repeat:
      for_each: "{{ devices }}"
      sequence:
        - domain: mobile_app
          type: notify
          device_id: "{{ repeat.item }}"
          title: "Leak detected!"
          message: "{{ leak_message }}"

  # Run any additional user-defined actions
  - sequence: !input leak_detected_actions

mode: single
